---
sudo: false
language: python
python:
  - "3.4"
  - "3.5"
  - "3.7"
  - "3.8"

matrix:
  fast_finish: true

env:
  - PIPENV_VERBOSITY=-1

install:
  - pip install --upgrade pipenv
  - pipenv install --dev

script:
  - pipenv run yapf -q -r bme280
  - pipenv run pylint --ignore=snapshots bme280 tests
  - pipenv run pytest
